name: GitHub Packages Image Deploy

on:
  workflow_dispatch: 
  push:
    branches: ["main", "develop"]

jobs:
  docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.1

      - name: Extract SERVER_VERSION from launch.sh
        id: extract-version
        run: |
          SERVER_VERSION=$(grep '^SERVER_VERSION=' launch.sh | cut -d '=' -f2 | tr -d '"')
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push the Docker image (versioned tag)
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/fabioazevedo0619/allthemods10:${{ env.SERVER_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push the Docker image (latest tag)
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/fabioazevedo0619/allthemods10:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
